const capitulos = [
    {
        id: 1,
        nombre_id: 1,
        temporada: 1,
        nombre: "1.Perdido en la Oscuridad",
        info: "Veinte años después de que un brote de hongos azote el planeta, a los sobrevivientes Joel y Tess les es asignada una misión que podría cambiarlo todo.",
        caratula: "../../assets/portadas/tlou_portada.jpeg",
        url: "../movies/tlou/s1/tlou0101.mp4",
    },
    {
        id: 2,
        nombre_id: 1,
        temporada: 1,
        nombre: "2.Infectados",
        info: "Tras escapar de la zona de cuarentena, Joel y Tess discuten sobre el destino de Ellie mientras atraviesan las ruinas de Boston.",
        caratula: "../../assets/portadas/tlou_portada.jpeg",
        url: "../movies/tlou/s1/tlou0102.mp4",
    },
    {
        id: 3,
        nombre_id: 2,
        temporada: 1,
        nombre: "1.Piloto",
        info: "En la víspera de un fatídico vuelo, un equipo campeón de fútbol femenil de preparatoria celebra traicionándose unas a otras. 25 años después",
        caratula: "../../assets/portadas/yellowjackets_portada.jpg",
        url: "../movies/yellowjackets/s1/yj0101.mkv",
    },
    {
        id: 4,
        nombre_id: 3,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/moanados.mp4",
    },
    {
        id: 16,
        nombre_id: 4,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/sonic3.MKV",
    },
    {
        id: 17,
        nombre_id: 5,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/mf.mkv",
    },
    {
        id: 18,
        nombre_id: 6,
        temporada: null,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/thegorge.mp4",
    },
    {
        id: 19,
        nombre_id: 1,
        temporada: 1,
        nombre: "3.Mucho, Mucho Tiempo",
        info: "Cuando un extraño se acerca al recinto de Bill, un aficionado en preparativos para escenarios apocalípticos, ambos forjan una conexión poco probable.",
        caratula: "../../assets/portadas/tlou_portada.jpeg",
        url: "../movies/tlou/s1/tlou0103.mp4",
    },
    {
        id: 20,
        nombre_id: 2,
        temporada: 1,
        nombre: "2. «Fa sostenido»",
        info: "Misty encuentra un propósito en el bosque. En el presente, Shauna tiene un accidente con un apuesto desconocido, mientras Natalie y Misty reciben postales misteriosas.",
        caratula: "../../assets/portadas/yellowjackets_portada.jpg",
        url: "../movies/yellowjackets/s1/yj0102.mkv",
    },
    {
        id: 21,
        nombre_id: 2,
        temporada: 1,
        nombre: "3. «La casa de las muñecas»",
        info: "Conmocionado, el equipo hace un funeral por las víctimas del accidente. Años más tarde, la campaña política de Taissa sufre críticas, y Shauna ya no confía en Jeff.",
        caratula: "../../assets/portadas/yellowjackets_portada.jpg",
        url: "../movies/yellowjackets/s1/yj0103.mkv",
    },
    {
        id: 22,
        nombre_id: 2,
        temporada: 1,
        nombre: "4.«Sigue pujando»",
        info: "Las Yellowjackets sobrevivientes deben elegir una cazadora, pero ¿quién tiene el mejor tiro? En una recaudación, Taissa se enfrenta a una aliada poderosa pero fisgona.",
        caratula: "../../assets/portadas/yellowjackets_portada.jpg",
        url: "../movies/yellowjackets/s1/yj0104.mkv",
    },
    {
        id: 23,
        nombre_id: 2,
        temporada: 1,
        nombre: "5. «Colmena de sangre»",
        info: "El equipo hace una sesión espiritista para levantar los ánimos. En 2021, Shauna intenta ocultar un secreto apasionado, y Taissa descubre algo inquietante.",
        caratula: "../../assets/portadas/yellowjackets_portada.jpg",
        url: "../movies/yellowjackets/s1/yj0105.mkv",
    },
    {
        id: 24,
        nombre_id: 2,
        temporada: 1,
        nombre: "6. «Santos»",
        info: "En el bosque, el romance florece entre los sobrevivientes. La Misty de hoy idea un plan para impedir que una periodista husmee en la vida de las Yellowjackets.",
        caratula: "../../assets/portadas/yellowjackets_portada.jpg",
        url: "../movies/yellowjackets/s1/yj0106.mkv",
    },
    {
        id: 25,
        nombre_id: 2,
        temporada: 1,
        nombre: "7. «Sin brújula»",
        info: "Taissa lidera una expedición en busca de civilización, o al menos de comida. Las mujeres montan una vigilancia con la esperanza de atrapar a quien intenta chantajearlas.",
        caratula: "../../assets/portadas/yellowjackets_portada.jpg",
        url: "../movies/yellowjackets/s1/yj0107.mkv",
    },
    {
        id: 26,
        nombre_id: 2,
        temporada: 1,
        nombre: "8. «El vuelo del abejorro»",
        info: "Las chicas reciben una sorpresa sórdida, y Laura Lee da un salto de fe. Mientras Misty intenta evitar que Natalie recaiga, Shauna busca información sobre Adam.",
        caratula: "../../assets/portadas/yellowjackets_portada.jpg",
        url: "../movies/yellowjackets/s1/yj0108.mkv",
    },
    {
        id: 27,
        nombre_id: 2,
        temporada: 1,
        nombre: "9. «Muerte próxima»",
        info: "Celebran la Muerte Próxima. Lottie inicia la noche de fiesta salvaje de las chicas con un discurso, pero el evento estridente pronto se sale de control.",
        caratula: "../../assets/portadas/yellowjackets_portada.jpg",
        url: "../movies/yellowjackets/s1/yj0109.mkv",
    },
    {
        id: 28,
        nombre_id: 2,
        temporada: 1,
        nombre: "10. «Sic Transit Gloria Mundi»",
        info: "Jackie enfrenta a Shauna por una traición dolorosa. Después de afrontar una tarea horrible, las Yellowjackets adultas asisten a su reunión de 25 años de la secundaria.",
        caratula: "../../assets/portadas/yellowjackets_portada.jpg",
        url: "../movies/yellowjackets/s1/yj0110.mkv",
    },
    {
        id: 29,
        nombre_id: 7,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/inc.mkv",
    },
    {
        id: 30,
        nombre_id: 8,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/mufasa.mp4",
    },
    {
        id: 31,
        nombre_id: 9,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/cordillera.mp4",
    },
    {
        id: 32,
        nombre_id: 10,
        temporada: null,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/gladiatordos.mkv",
    },
    {
        id: 33,
        nombre_id: 11,
        temporada: null,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/nakedgun.mp4",
    },
    {
        id: 34,
        nombre_id: 12,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/nok.mp4",
    },
    {
        id: 35,
        nombre_id: 13,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/markedones.mkv",
    },
    {
        id: 36,
        nombre_id: 14,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/dim_desc.mp4",
    },
    {
        id: 37,
        nombre_id: 15,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/electric_state.mkv",
    },
    {
        id: 38,
        nombre_id: 19,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/relatos.mkv",
    },
    {
        id: 39,
        nombre_id: 16,
        temporada: 2,
        nombre: "1.Hola, señora Cobel",
        info: "Mark vuelve al trabajo, pero las circunstancias han cambiado. Salen a la luz secretos del mundo exterior.",
        caratula: "../../assets/portadas/severance_portada.jpg",
        url: "../movies/severance/severance0201.mkv",
    },
    {
        id: 40,
        nombre_id: 16,
        temporada: 2,
        nombre: "2.Adiós, señora Selvig",
        info: "El fueri de Mark se plantea el significado de un mensaje. Lumon se enfrenta a las consecuencias de la Contingencia de Horas Extra.",
        caratula: "../../assets/portadas/severance_portada.jpg",
        url: "../movies/severance/severance0202.mkv",
    },
    {
        id: 41,
        nombre_id: 16,
        temporada: 2,
        nombre: "3.¿Quién está vivo?",
        info: "Mark y Helly regresan a un antiguo refugio. Irving y Dylan hacen averiguaciones por separado. El fueri de Mark prueba algo nuevo.",
        caratula: "../../assets/portadas/severance_portada.jpg",
        url: "../movies/severance/severance0203.mkv",
    },
    {
        id: 42,
        nombre_id: 16,
        temporada: 2,
        nombre: "4.El abismo de Aflicción",
        info: "El equipo atraviesa un terreno desconocido. Mark y Helly exploran sus sentimientos. Irving desconfía cada vez más de un amigo.",
        caratula: "../../assets/portadas/severance_portada.jpg",
        url: "../movies/severance/severance0204.mkv",
    },
    {
        id: 43,
        nombre_id: 17,
        temporada: 1,
        nombre: "T1:E1.Tarjeta de Navidad",
        info: "El grupo ayuda a una pareja desesperada a volver a estar juntos",
        caratula: "../../assets/portadas/simuladores_portada.jpeg",
        url: "https://archive.org/download/los-simuladores-2002/T1-01.%20Tarjeta%20de%20Navidad%20%5B480p%5D.ia.mp4",
    },
    {
        id: 44,
        nombre_id: 17,
        temporada: 1,
        nombre: "T1:E2.Diagnóstico rectoscópico",
        info: "Un dueño de un locutorio se endeuda con un mafioso que amenaza con matar a sus hijos si no le paga pronto.",
        caratula: "../../assets/portadas/simuladores_portada.jpeg",
        url: "https://archive.org/download/los-simuladores-2002/T1-02.%20Diagn%C3%B3stico%20rectosc%C3%B3pico%20%5B480p%5D.ia.mp4",
    },
    {
        id: 45,
        nombre_id: 17,
        temporada: 1,
        nombre: "T1:E3.Seguro de desempleo",
        info: "Un empleado de una lechería es despedido por ser ya mayor. Incapaz de encontrar otro trabajo por su edad, pide ayuda a los Simuladores para conservar su puesto",
        caratula: "../../assets/portadas/simuladores_portada.jpeg",
        url: "https://archive.org/download/los-simuladores-2002/T1-03.%20Seguro%20de%20desempleo%20%5B480p%5D.ia.mp4",
    },
    {
        id: 46,
        nombre_id: 17,
        temporada: 1,
        nombre: "T1:E4.El testigo español",
        info: "Una mujer es acosada por un amante extranjero que conoció en Miami, poniendo en riesgo su matrimonio. Los simuladores recrean conspiración policíaca para espantarlo del país.",
        caratula: "../../assets/portadas/simuladores_portada.jpeg",
        url: "https://archive.org/download/los-simuladores-2002/T1-04.%20El%20testigo%20espa%C3%B1ol%20%5B480p%5D.ia.mp4",
    },
    {
        id: 47,
        nombre_id: 17,
        temporada: 1,
        nombre: "T1:E5.El joven simulador",
        info: "El hijo de un arquitecto está a punto de repetir de año podría empeorar la situación. Los simuladores deberán ayudarlo a aprobar 7 exámenes para poder pasar de año.",
        caratula: "../../assets/portadas/simuladores_portada.jpeg",
        url: "https://archive.org/download/los-simuladores-2002/T1-05.%20El%20joven%20simulador%20%5B480p%5D.ia.mp4",
    },
    {
        id: 48,
        nombre_id: 17,
        temporada: 1,
        nombre: "T1:E6.El pequeño problema",
        info: "El Presidente tiene disfunción erectil y es incapaz de complacer a su mujer. Ella contrata a los simuladores para que lo ayuden a recuperar sus habilidades en la cama.",
        caratula: "../../assets/portadas/simuladores_portada.jpeg",
        url: "https://archive.org/download/los-simuladores-2002/T1-06.%20El%20peque%C3%B1o%20problema%20del%20gran%20hombre%20%5B480p%5D.ia.mp4",
    },
    {
        id: 49,
        nombre_id: 17,
        temporada: 1,
        nombre: "T1:E7.Fuera de cálculo",
        info: "Un operativo montado por los Simuladores en un banco es interrumpido por un robo. El grupo deberá ayudar a los ladrones luego de descubrir que el jefe comisario es corupto.",
        caratula: "../../assets/portadas/simuladores_portada.jpeg",
        url: "https://archive.org/download/los-simuladores-2002/T1-07.%20Fuera%20de%20c%C3%A1lculo%20%5B480p%5D.ia.mp4",
    },
    {
        id: 50,
        nombre_id: 17,
        temporada: 1,
        nombre: "T1:E8.El pacto Copérnico",
        info: "Un abogado contrata la ayuda de los simuladores para que su mujer se enamore de alguien más, y Hacen creer a un hombre que es la clave en un plan de los Nazis.",
        caratula: "../../assets/portadas/simuladores_portada.jpeg",
        url: "https://archive.org/download/los-simuladores-2002/T1-08.%20El%20pacto%20Cop%C3%A9rnico%20%5B480p%5D.ia.mp4",
    },
    {
        id: 51,
        nombre_id: 17,
        temporada: 1,
        nombre: "T1:E9.El último héroe",
        info: "Un hombre estafa a una familia de clase baja. Ellos tratarán de recuperar lo perdido contratando a los Simuladores.",
        caratula: "../../assets/portadas/simuladores_portada.jpeg",
        url: "https://archive.org/download/los-simuladores-2002/T1-09.%20El%20%C3%BAltimo%20h%C3%A9roe%20%5B480p%5D.ia.mp4",
    },
    {
        id: 52,
        nombre_id: 17,
        temporada: 1,
        nombre: "T1:E10.Los impresentables",
        info: "Una mujer pide ayuda a los Simuladores cuando debe presentar su familia \"impresentable\" a la familia de su novio.",
        caratula: "../../assets/portadas/simuladores_portada.jpeg",
        url: "https://archive.org/download/los-simuladores-2002/T1-10.%20Los%20impresentables%20%5B480p%5D.ia.mp4",
    },
    {
        id: 53,
        nombre_id: 17,
        temporada: 1,
        nombre: "T1:E11.El colaborador foráneo",
        info: "Crucitti is a corrupt sheriff on a non-specified city of Buenos Aires. The group of \"Los Simuladores\" will make him change.",
        caratula: "../../assets/portadas/simuladores_portada.jpeg",
        url: "https://archive.org/download/los-simuladores-2002/T1-11.%20El%20colaborador%20for%C3%A1neo%20%5B480p%5D.ia.mp4",
    },
    {
        id: 54,
        nombre_id: 17,
        temporada: 1,
        nombre: "T1:E12.Marcela & Paul",
        info: "El grupo ayuda a una mujer recientemente divorciada a recuperar su amor propio y ganas de vivir, organizándole una cena con el que ella piensa es el auténtico Paul McCartney.",
        caratula: "../../assets/portadas/simuladores_portada.jpeg",
        url: "https://archive.org/download/los-simuladores-2002/T1-12.%20Marcela%20%26%20Paul%20%5B480p%5D.ia.mp4",
    },
    {
        id: 55,
        nombre_id: 17,
        temporada: 1,
        nombre: "T1:E13.Un trabajo involuntario",
        info: "Los Simuladores son extorsionados para hacer un trabajo a cambio de la vida de Santos.",
        caratula: "../../assets/portadas/simuladores_portada.jpeg",
        url: "https://archive.org/download/los-simuladores-2002/T1-13.%20Un%20trabajo%20involuntario%20%5B480p%5D.ia.mp4",
    },
    {
        id: 66,
        nombre_id: 21,
        temporada: 1,
        nombre: "1. El viaje del día a la noche",
        info: "El viaje por carretera de los Matthew da un macabro giro cuando se desvían y llegan a un pueblo del que no pueden salir.",
        caratula: "../../assets/portadas/from_portada.jpeg",
        url: "../movies/from/s1/from0101.mp4",
    },
    {
        id: 67,
        nombre_id: 21,
        temporada: 1,
        nombre: "2. Cómo son las cosas ahora",
        info: "Tabitha y Julie se adaptan a la terrible realidad en Colony House. En el bosque, Jim, Boyd y Kristi tienen problemas para tratar a Ethan.",
        caratula: "../../assets/portadas/from_portada.jpeg",
        url: "../movies/from/s1/from0102.mp4",
    },
    {
        id: 68,
        nombre_id: 21,
        temporada: 1,
        nombre: "3. El día de la elección",
        info: "La familia Matthew debe escoger a qué asentamiento se unirán. Mientras tanto, Jade acepta su situación y Boyd debe tomar una decisión muy difícil",
        caratula: "../../assets/portadas/from_portada.jpeg",
        url: "../movies/from/s1/from0103.mp4",
    },
    {
        id: 69,
        nombre_id: 21,
        temporada: 1,
        nombre: "4. Una roca y una lejanía",
        info: "Julie se refugia en sus nuevos amigos. Jim y Tabitha lidian con los problemas de su matrimonio. Ethan y Victor se adentran en el bosque.",
        caratula: "../../assets/portadas/from_portada.jpeg",
        url: "../movies/from/s1/from0104.mp4",
    },
    {
        id: 70,
        nombre_id: 21,
        temporada: 1,
        nombre: "5. Siluetas",
        info: "Jim, Tabitha e Ethan hacen preguntas sobre el lugar con la esperanza de regresar. Ellis y Fatima le muestran a Julie la parte divertida del pueblo.",
        caratula: "../../assets/portadas/from_portada.jpeg",
        url: "../movies/from/s1/from0105.mp4",
    },
    {
        id: 71,
        nombre_id: 21,
        temporada: 1,
        nombre: "6. Libro 74",
        info: "ade le pide ayuda a Jim con un experimento, mientras Tabitha descubre algo escalofriante que hace que busque respuestas en un lugar único.",
        caratula: "../../assets/portadas/from_portada.jpeg",
        url: "../movies/from/s1/from0106.mp4",
    },
    {
        id: 72,
        nombre_id: 21,
        temporada: 1,
        nombre: "7. Todas las cosas buenas",
        info: "Jim y Tabitha se consuelan el uno al otro. Colony House celebra el primer aniversario de la llegada de Fatima con una fiesta que sale muy mal.",
        caratula: "../../assets/portadas/from_portada.jpeg",
        url: "../movies/from/s1/from0107.mp4",
    },
    {
        id: 73,
        nombre_id: 21,
        temporada: 1,
        nombre: "8. Ventanas,puertas abiertas",
        info: "Kenny acepta su nuevo rol. Jim propone construir una torre de telecomunicaciones. Fatima le pide a Ellis que arregle las cosas con su padre.",
        caratula: "../../assets/portadas/from_portada.jpeg",
        url: "../movies/from/s1/from0108.mp4",
    },
    {
        id: 74,
        nombre_id: 21,
        temporada: 1,
        nombre: "9. En los bosques",
        info: "Boyd y Sara se adentran en el bosque y se encuentran más misterios terroríficos. Jim empieza a perder la confianza en la torre de telecomunicaciones.",
        caratula: "../../assets/portadas/from_portada.jpeg",
        url: "../movies/from/s1/from0109.mp4",
    },
    {
        id: 75,
        nombre_id: 21,
        temporada: 1,
        nombre: "10.los sitios donde iremos",
        info: "Boyd encuentra fuerza en algo inesperado. El agujero que Tabitha está cavando lleva a un lugar, y a una persona, que no esperaba. Todo cambiará.",
        caratula: "../../assets/portadas/from_portada.jpeg",
        url: "../movies/from/s1/from0110.mp4",
    },
    {
        id: 76,
        nombre_id: 22,
        temporada: 1,
        nombre: "1.Bienvenidos a margrave",
        info: "Reacher es injustamente acusado de homicidio mientras visitaba el pequeño pueblo de Margrave, Gerogia.",
        caratula: "../../assets/portadas/reacher_portada.webp",
        url: "../movies/reacher/s1/reacher0101.mp4",
    },
    {
        id: 77,
        nombre_id: 22,
        temporada: 1,
        nombre: "2.Primer baile",
        info: "Cuando más víctimas son descubiertas, Reacher intenta obtener respuestas, pero le tienden una trampa. Roscoe recibe un mensaje amenazante.",
        caratula: "../../assets/portadas/reacher_portada.webp",
        url: "../movies/reacher/s1/reacher0102.mp4",
    },
    {
        id: 78,
        nombre_id: 22,
        temporada: 1,
        nombre: "3.Cucharada",
        info: "La investigación de Reacher y Finlay sobre la desaparición de Spivey los lleva a confrontar a Kilner. Roscoe recibe inquietantes noticias sobre Reacher.",
        caratula: "../../assets/portadas/reacher_portada.webp",
        url: "../movies/reacher/s1/reacher0103.mp4",
    },
    {
        id: 79,
        nombre_id: 22,
        temporada: 1,
        nombre: "4.Un arbol",
        info: "Mientras el peligro aumenta, Reacher y Roscoe se hacen más cercanos y hacen planes para encontrarse con su contacto de Seguridad Nacional.",
        caratula: "../../assets/portadas/reacher_portada.webp",
        url: "../movies/reacher/s1/reacher0104.mp4",
    },
    {
        id: 80,
        nombre_id: 22,
        temporada: 1,
        nombre: "5.Sin disculpas",
        info: "Mientras el misterio crece, Reacher hace equipo con una antigua colega y Finlay hace un descubrimiento estremecedor.",
        caratula: "../../assets/portadas/reacher_portada.webp",
        url: "../movies/reacher/s1/reacher0105.mp4",
    },
    {
        id: 81,
        nombre_id: 22,
        temporada: 1,
        nombre: "6.Papel",
        info: "Cuando el pueblo es agitado con otro asesinato, Reacher viaja a Nueva York y se entera de la verdad sobre el negocio ilegal en Margrave mientras que Roscoe enfrenta un ataque en el bosque.",
        caratula: "../../assets/portadas/reacher_portada.webp",
        url: "../movies/reacher/s1/reacher0106.mp4",
    },
    {
        id: 82,
        nombre_id: 22,
        temporada: 1,
        nombre: "7.Reacher no habló",
        info: "Reacher prepara una trampa y es él quien es atrapado.",
        caratula: "../../assets/portadas/reacher_portada.webp",
        url: "../movies/reacher/s1/reacher0107.mp4",
    },
    {
        id: 83,
        nombre_id: 22,
        temporada: 1,
        nombre: "8.Pay",
        info: "Reacher dirige una misión de rescate en la bodega y termina en un enfretnamiento.",
        caratula: "../../assets/portadas/reacher_portada.webp",
        url: "../movies/reacher/s1/reacher0108.mp4",
    },
    {
        id: 84,
        nombre_id: 23,
        temporada: 1,
        nombre: "1. «Episodio 1»",
        info: "La policía derriba la puerta del hogar de los Miller. El adolescente Jamie es arrestado y llevado a la comisaría para un interrogatorio, pero insiste en que no ha hecho nada malo.",
        caratula: "../../assets/portadas/ad_portada.jpg",
        url: "../movies/adolecence/ad0101.mkv",
    },
    {
        id: 85,
        nombre_id: 23,
        temporada: 1,
        nombre: "2. «Episodio 2»",
        info: "La policía busca respuestas —y el arma homicida— en la escuela de Jamie. No obtienen información de los amigos del chico, hasta que el hijo del detective Bascombe ofrece su ayuda.",
        caratula: "../../assets/portadas/ad_portada.jpg",
        url: "../movies/adolecence/ad0102.mkv",
    },
    {
        id: 86,
        nombre_id: 23,
        temporada: 1,
        nombre: "3. «Episodio 3»",
        info: "Jamie se reúne con una psicóloga. Al principio, no quiere hablar, pero después se sincera sobre sus complejos sentimientos hacia Katie.",
        caratula: "../../assets/portadas/ad_portada.jpg",
        url: "../movies/adolecence/ad0103.mkv",
    },
    {
        id: 87,
        nombre_id: 23,
        temporada: 1,
        nombre: "4. «Episodio 4»",
        info: "En el cumpleaños de Eddie, los Miller intentan festejar como si todo estuviera bien, pero una serie de sucesos imprevistos amenaza con desestabilizarlos.",
        caratula: "../../assets/portadas/ad_portada.jpg",
        url: "../movies/adolecence/ad0104.mkv",
    },
    {
        id: 88,
        nombre_id: 24,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/miky.mp4",
    },
    {
        id: 95,
        nombre_id: 26,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/df3.mp4",
    },
    {
        id: 96,
        nombre_id: 27,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/df4.mp4",
    },
    {
        id: 97,
        nombre_id: 28,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/df5.mp4",
    },
    {
        id: 98,
        nombre_id: 29,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/capambnw.mkv",
    },
    {
        id: 99,
        nombre_id: 30,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/novocaine.mkv",
    },
    {
        id: 100,
        nombre_id: 1,
        temporada: 2,
        nombre: "1. Días Futuros",
        info: "Cinco años después de los eventos de la tempórada 1, Joel y Ellie se ven envueltos en un conflicto en un mundo aún mas peligroso",
        caratula: "../../assets/portadas/tlou_portada.jpeg",
        url: "../movies/tlou/s2/tlou0201.mp4",
    },
    {
        id: 102,
        nombre_id: 32,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/awman.mp4",
    },
    {
        id: 103,
        nombre_id: 33,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/idepol.mkv",
    },
    {
        id: 104,
        nombre_id: 1,
        temporada: 2,
        nombre: "2. Trough The Valley",
        info: "Mientras Abby sopesa sus opciones, Jackson Hole se prepara para una tormenta en medio de crecientes avistamientos de Infectados",
        caratula: "../../assets/portadas/tlou_portada.jpeg",
        url: "../movies/tlou/s2/tlou0202.mkv",
    },
    {
        id: 105,
        nombre_id: 34,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/ash.mkv",
    },
    {
        id: 106,
        nombre_id: 1,
        temporada: 2,
        nombre: "3. El Camino",
        info: "Tras recibir información de Dina, Ellie prepara una petición al consejo del pueblo. Cerca de Seattle, un grupo religioso huye de una guerra.",
        caratula: "../../assets/portadas/tlou_portada.jpeg",
        url: "../movies/tlou/s2/tlou0203.mp4",
    },
    {
        id: 107,
        nombre_id: 35,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/ngtree.mkv",
    },
    {
        id: 108,
        nombre_id: 36,
        temporada: 1,
        nombre: "1. «Noche de truco»",
        info: "Una nevada insólita interrumpe la noche de truco de Juan y sus amigos. Entre la incertidumbre y las tensiones, improvisan un traje para que él enfrente la nieve y busque a su hija.",
        caratula: "../../assets/portadas/eternauta_portada.png",
        url: "../movies/eternauta/s1/eternauta0101.mkv",
    },
    {
        id: 109,
        nombre_id: 36,
        temporada: 1,
        nombre: "2. «Salgan al sol»",
        info: "Luego de atravesar una asolada ciudad de Buenos Aires para llegar al departamento de Elena y Clara, Juan descubre que el instinto humano puede ser tan letal como la nieve tóxica",
        caratula: "../../assets/portadas/eternauta_portada.png",
        url: "../movies/eternauta/s1/eternauta0102.mkv",
    },
    {
        id: 110,
        nombre_id: 36,
        temporada: 1,
        nombre: "3. «El magnetismo»",
        info: "En busca de pistas en el colegio de Clara, Juan y Elena conocen a Pablo, un alumno angustiado. El Tano intenta comunicarse por radio, y las visiones de Juan se intensifican.",
        caratula: "../../assets/portadas/eternauta_portada.png",
        url: "../movies/eternauta/s1/eternauta0103.mkv",
    },
    {
        id: 111,
        nombre_id: 36,
        temporada: 1,
        nombre: "4. «Credo»",
        info: "El Tano y Juan se dirigen al centro, donde encuentran una barricada y a las fuerzas militares. Después de toparse con una amenaza repulsiva, reciben ayuda de un grupo muy peculiar.",
        caratula: "../../assets/portadas/eternauta_portada.png",
        url: "../movies/eternauta/s1/eternauta0104.mkv",
    },
    {
        id: 112,
        nombre_id: 36,
        temporada: 1,
        nombre: "5. «Paisaje»",
        info: "Con la isla como destino, el Tano tiene que tomar una decisión difícil para conseguir transporte. En el camino, descubren un campo de refugiados adentro de un shopping.",
        caratula: "../../assets/portadas/eternauta_portada.png",
        url: "../movies/eternauta/s1/eternauta0105.mkv",
    },
    {
        id: 113,
        nombre_id: 36,
        temporada: 1,
        nombre: "6. «Jugo de tomate frío»",
        info: "Después de una arriesgada misión en tren para volver a la ciudad, una misteriosa luz brillante atrae a Juan y lo conduce a un descubrimiento inimaginable.",
        caratula: "../../assets/portadas/eternauta_portada.png",
        url: "../movies/eternauta/s1/eternauta0106.mkv",
    },
    {
        id: 114,
        nombre_id: 37,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/conclave.mkv",
    },
    {
        id: 115,
        nombre_id: 38,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/mono.mkv",
    },
    {
        id: 124,
        nombre_id: 40,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/minecraft.mp4",
    },
    {
        id: 125,
        nombre_id: 41,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/warfare.mp4",
    },
    {
        id: 126,
        nombre_id: 42,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/white.mp4",
    },
    {
        id: 127,
        nombre_id: 43,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/superhero.mp4",
    },
    {
        id: 128,
        nombre_id: 43,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/superhero.mp4",
    },
    {
        id: 129,
        nombre_id: 44,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/acused.mkv",
    },
    {
        id: 130,
        nombre_id: 45,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/Until.Dawn.mkv",
    },
    {
        id: 131,
        nombre_id: 46,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/stitch.mkv",
    },
    {
        id: 132,
        nombre_id: 47,
        temporada: 1,
        nombre: "1. El último día",
        info: "En todo el mundo comienzan a producirse sucesos extraños e inexplicables. Un sheriff de un pequeño pueblo presiente que se trata de algo más grande.",
        caratula: "../../assets/portadas/invasion_portada.jpg",
        url: "../movies/invasion/s1/invasion0101.mp4",
    },
    {
        id: 133,
        nombre_id: 47,
        temporada: 1,
        nombre: "2.Accidente",
        info: "En medio del caos, Aneesha toma una difícil decisión por el bien de su familia. Trevante, del cuerpo especial de la Marina, investiga una llamada de auxilio con su equipo.",
        caratula: "../../assets/portadas/invasion_portada.jpg",
        url: "../movies/invasion/s1/invasion0102.mp4",
    },
    {
        id: 134,
        nombre_id: 47,
        temporada: 1,
        nombre: "3.Orion",
        info: "Mitsuki toma medidas desesperadas, decidida a descubrir la verdad. Caspar y Jamila descubren lo grave que es su situación.",
        caratula: "../../assets/portadas/invasion_portada.jpg",
        url: "../movies/invasion/s1/invasion0103.mp4",
    },
    {
        id: 135,
        nombre_id: 47,
        temporada: 1,
        nombre: "4.El rey ha muerto",
        info: "Trevante se teme lo peor hasta que una baliza de localización le da esperanzas. Mitsuki encuentra un aliado en el lugar más inesperado.",
        caratula: "../../assets/portadas/invasion_portada.jpg",
        url: "../movies/invasion/s1/invasion0104.mp4",
    },
    {
        id: 136,
        nombre_id: 47,
        temporada: 1,
        nombre: "5.Camino a casa",
        info: "La presidenta de los Estados Unidos pronuncia un discurso global urgente para preparar al mundo para lo que se avecina.",
        caratula: "../../assets/portadas/invasion_portada.jpg",
        url: "../movies/invasion/s1/invasion0105.mp4",
    },
    {
        id: 137,
        nombre_id: 48,
        temporada: 0,
        nombre: "T1:E1.¡Bienvenidos!",
        info: "Las hermanas huérfanas Vi y Powder causan problemas en las calles clandestinas de Zaun tras un robo en la lujosa ciudad de Piltóver.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s1/arcane0101.mp4",
    },
    {
        id: 138,
        nombre_id: 48,
        temporada: 1,
        nombre: "T1:E2.Misterios sin resolver",
        info: "El idealista inventor Jayce intenta dominar la magia con la ciencia, a pesar de los consejos de su mentor. El líder criminal Silco experimenta con una poderosa sustancia.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s1/arcane0102.mp4",
    },
    {
        id: 139,
        nombre_id: 48,
        temporada: 1,
        nombre: "T1:E3.La violencia para el cambio",
        info: "Un enfrentamiento épico entre viejos rivales trae graves consecuencias para la localidad de Zaun. Jayce y Viktor lo arriesgan todo por su investigación.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s1/arcane0103.mp4",
    },
    {
        id: 140,
        nombre_id: 48,
        temporada: 1,
        nombre: "T1:E4.¡Feliz Día del Progreso!",
        info: "Ya que Piltóver se está beneficiando de su tecnología, Jayce y Viktor piensan en el siguiente paso. Una cara familiar de Zaun reaparece y provoca un caos",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s1/arcane0104.mp4",
    },
    {
        id: 141,
        nombre_id: 48,
        temporada: 1,
        nombre: "T1:E5.Todos quieren ser mi enemigo",
        info: "La rebelde vigilante Caitlyn recorre el distrito suburbano para localizar a Silco. Jayce se convierte en un blanco al intentar erradicar la corrupción en Piltóver.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s1/arcane0105.mp4",
    },
    {
        id: 142,
        nombre_id: 48,
        temporada: 1,
        nombre: "T1:E6.Cuando caigan estos muros",
        info: "Un protegido menoscaba a su tutor en el Consejo, mientras una tecnología mágica evoluciona rápidamente. Con las autoridades detrás de ella, Jinx debe afrontar su pasado.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s1/arcane0106.mp4",
    },
    {
        id: 143,
        nombre_id: 48,
        temporada: 1,
        nombre: "T1:E7.El salvador",
        info: "Caitlyn y Vi se reúnen en un callejón de Zaun y se dirigen hacia una frenética pelea con una enemiga en común. Viktor toma una complicada decisión.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s1/arcane0107.mp4",
    },
    {
        id: 144,
        nombre_id: 48,
        temporada: 1,
        nombre: "T1:E8.Agua y aceite",
        info: "La desterrada heredera Mel y su madre, que está de visita, intercambian tácticas de combate. Caitlyn y Vi forman una inesperada alianza. Jinx tiene un cambio impactante.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s1/arcane0108.mp4",
    },
    {
        id: 145,
        nombre_id: 48,
        temporada: 1,
        nombre: "T1:E9.El monstruo que creaste",
        info: "Cuando la guerra acecha peligrosamente, los líderes de Piltóver y Zaun reciben un ultimátum. Pero un enfrentamiento fatídico cambia ambas ciudades para siempre.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s1/arcane0109.mp4",
    },
    {
        id: 146,
        nombre_id: 47,
        temporada: 1,
        nombre: "6.Invasión en casa",
        info: "Conmocionada por el discurso de la presidenta, Aneesha vuelve con su familia y se encuentra con que su refugio seguro -y sus vidas- están en peligro.",
        caratula: "../../assets/portadas/invasion_portada.jpg",
        url: "../movies/invasion/s1/invasion0106.mp4",
    },
    {
        id: 147,
        nombre_id: 47,
        temporada: 1,
        nombre: "7.Esperanza",
        info: "Mitsuki se apropia de una estación de satélites con la esperanza de establecer contacto con el espacio exterior. Caspar revela un extraño secreto que cree que está relacionado con la invasión.",
        caratula: "../../assets/portadas/invasion_portada.jpg",
        url: "../movies/invasion/s1/invasion0107.mp4",
    },
    {
        id: 148,
        nombre_id: 47,
        temporada: 1,
        nombre: "8.Contacto",
        info: "El avión de Trevante aterriza, pero su viaje a casa no ha hecho más que empezar. Caspar y Jamila se enfrentan a las calles de Londres, intentando dar sentido a su secreto.",
        caratula: "../../assets/portadas/invasion_portada.jpg",
        url: "../movies/invasion/s1/invasion0108.mp4",
    },
    {
        id: 149,
        nombre_id: 47,
        temporada: 1,
        nombre: "9.Lleno de estrellas",
        info: "Mitsuki está decidida a ponerse en contacto con la Hoshi 12 antes de que sea demasiado tarde. Los militares detienen a los Malik y Caspar corre un riesgo que puede matarlo.",
        caratula: "../../assets/portadas/invasion_portada.jpg",
        url: "../movies/invasion/s1/invasion0109.mp4",
    },
    {
        id: 150,
        nombre_id: 47,
        temporada: 1,
        nombre: "10.El primer día",
        info: "El mundo, que aún se tambalea por la destrucción global, se enfrenta a un nuevo e imprevisto amanecer.",
        caratula: "../../assets/portadas/invasion_portada.jpg",
        url: "../movies/invasion/s1/invasion0110.mp4",
    },
    {
        id: 151,
        nombre_id: 47,
        temporada: 2,
        nombre: "1.Ha cambiado algo",
        info: "Llevan a Mitsuki a una nave alienígena en la selva amazónica. Aneesha y sus hijos se refugian con un grupo llamado el Movimiento.",
        caratula: "../../assets/portadas/invasion_portada.jpg",
        url: "../movies/invasion/s2/invasion0201.mp4",
    },
    {
        id: 152,
        nombre_id: 47,
        temporada: 2,
        nombre: "2.Persiguiendo fantasmas",
        info: "En su casa de Miami, Trevante lucha por volver a la vida cotidiana. Del mismo modo, Jamila siente la necesidad constante de buscar a Caspar.",
        caratula: "../../assets/portadas/invasion_portada.jpg",
        url: "../movies/invasion/s2/invasion0202.mp4",
    },
    {
        id: 153,
        nombre_id: 47,
        temporada: 2,
        nombre: "3.Fuegos artificiales",
        info: "Un descubrimiento determinante podría dar por fin ventaja a la Tierra. A Aneesha le cuesta confiar en el Movimiento, a pesar de necesitar su ayuda.",
        caratula: "../../assets/portadas/invasion_portada.jpg",
        url: "../movies/invasion/s2/invasion0203.mp4",
    },
    {
        id: 154,
        nombre_id: 47,
        temporada: 2,
        nombre: "4.El túnel",
        info: "La decisión de Jamila de atravesar el túnel del Canal enfrenta al grupo a un enemigo aún más mortífero.",
        caratula: "../../assets/portadas/invasion_portada.jpg",
        url: "../movies/invasion/s2/invasion0204.mp4",
    },
    {
        id: 155,
        nombre_id: 48,
        temporada: 2,
        nombre: "T2:E1.El peso del liderazgo",
        info: "Vi y Caitlyn intentan encontrar la mejor respuesta ante una terrible tragedia que se cobra vidas y profundiza tensiones entre las ciudades gemelas.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s2/arcane0201.mkv",
    },
    {
        id: 156,
        nombre_id: 48,
        temporada: 2,
        nombre: "T2:E2.Ver cómo se quema todo",
        info: "Piltóver está lista para pelear, mientras el distrito subterráneo evalúa sus opciones. Jinx se mantiene al margen y planea su próxima jugada. Una conversación clave tiene lugar.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s2/arcane0202.mkv",
    },
    {
        id: 157,
        nombre_id: 48,
        temporada: 2,
        nombre: "T2:E3.Por fin dijiste mi nombre",
        info: "Caitlyn redobla sus esfuerzos de encontrar a Jinx, y Ambessa acepta una fatídica reunión. Cambios en Zaun revelan un descubrimiento impactante.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s2/arcane0203.mkv",
    },
    {
        id: 158,
        nombre_id: 48,
        temporada: 2,
        nombre: "T2:E4.Pintemos la ciudad de azul",
        info: "Mientras crecen los rumores sobre el regreso de Jinx, Ambessa persigue a su objetivo con nuevos bríos. Jinx y Sevika, de incógnito, se adentran en la boca del lobo.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s2/arcane0204.mkv",
    },
    {
        id: 159,
        nombre_id: 48,
        temporada: 2,
        nombre: "T2:E5.Ampollas y piedra",
        info: "Vi se entera de algo sorprendente al despertar. Un inquietante reencuentro no es lo que parece. Caitlyn revela el origen del Brillo.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s2/arcane0205.mkv",
    },
    {
        id: 160,
        nombre_id: 48,
        temporada: 2,
        nombre: "T2:E6.El mensaje oculto en el patrón",
        info: "La recuperación viene acompañada de un rostro conocido…, en un lugar poco familiar. Una traición sorprendente podría cambiar muchísimas vidas.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s2/arcane0206.mkv",
    },
    {
        id: 161,
        nombre_id: 48,
        temporada: 2,
        nombre: "T2:E7.Finjamos que es la primera vez",
        info: "Un instante de oscuridad, un instante de luz y una visión de lo que pudo ser... y no fue.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s2/arcane0207.mkv",
    },
    {
        id: 162,
        nombre_id: 48,
        temporada: 2,
        nombre: "T2:E8.Matar es un ciclo",
        info: "La tormenta se aproxima, causando grandes transformaciones. En otro lugar, una chispa de rebelión sigue ardiendo.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s2/arcane0208.mkv",
    },
    {
        id: 163,
        nombre_id: 48,
        temporada: 2,
        nombre: "T2:E9.La mugre bajo tus uñas",
        info: "Magia, ciencia, poder, venganza: en este épico capítulo final, el choque de diferentes destinos enciende una guerra sin freno.",
        caratula: "../../assets/portadas/arcane_portada.webp",
        url: "../movies/arcane/s2/arcane0209.mkv",
    },
    {
        id: 164,
        nombre_id: 49,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/juventud.mkv",
    },
    {
        id: 165,
        nombre_id: 50,
        temporada: 1,
        nombre: "T1:E1.La paz del emperador",
        info: "Gaal Dornick deja atrás su vida en Synnax cuando el matemático más importante de la galaxia, Hari Seldon, la invita a Trántor.",
        caratula: "../../assets/portadas/foundation_portada.jpg",
        url: "../movies/foundation/s1/foundation0101.mp4",
    },
    {
        id: 166,
        nombre_id: 50,
        temporada: 1,
        nombre: "T1:E2.Prepararse para vivir",
        info: "La Fundación emprende su largo viaje a Términus y, en el camino, Gaal y Raych intiman cada vez más. El Imperio afronta una difícil decisión.",
        caratula: "../../assets/portadas/foundation_portada.jpg",
        url: "../movies/foundation/s1/foundation0102.mp4",
    },
    {
        id: 167,
        nombre_id: 50,
        temporada: 1,
        nombre: "T1:E3.Fantasma del matemático",
        info: "Hermano Ocaso reflexiona sobre su legado mientras se prepara para la ascención. La Fundación llega a Términus y encuentra un objeto misterioso.",
        caratula: "../../assets/portadas/foundation_portada.jpg",
        url: "../movies/foundation/s1/foundation0103.mp4",
    },
    {
        id: 168,
        nombre_id: 50,
        temporada: 1,
        nombre: "T1:E4.Bárbaros a las puertas",
        info: "Salvor planta cara a una enemiga del Imperio. Los Hermanos Día y Descenso tienen un desacuerdo, mientras el Hermano Despunte debe lidiar con su verdad.",
        caratula: "../../assets/portadas/foundation_portada.jpg",
        url: "../movies/foundation/s1/foundation0104.mp4",
    },
    {
        id: 169,
        nombre_id: 50,
        temporada: 1,
        nombre: "T1:E5.Al despertar",
        info: "Un flashback revela el origen del conflicto de Gaal entre la fe y la ciencia. El enfrentamiento en Términus da un giro desafortunado.",
        caratula: "../../assets/portadas/foundation_portada.jpg",
        url: "../movies/foundation/s1/foundation0105.mp4",
    },
    {
        id: 170,
        nombre_id: 50,
        temporada: 1,
        nombre: "T1:E6.La muerte y la Doncella",
        info: "El Hermano Día conoce a la Céfira Halima, una aspirante a líder contraria al Imperio. El Hermano Descenso empieza a sospechar del Hermano Despunte.",
        caratula: "../../assets/portadas/foundation_portada.jpg",
        url: "../movies/foundation/s1/foundation0106.mp4",
    },
    {
        id: 171,
        nombre_id: 50,
        temporada: 1,
        nombre: "T1:E7.Misterios y mártires",
        info: "Los anacreontes y sus rehenes abordan la legendaria nave de guerra Invictus. El vínculo entre el Hermano Despunte y Azura se afianza.",
        caratula: "../../assets/portadas/foundation_portada.jpg",
        url: "../movies/foundation/s1/foundation0107.mp4",
    },
    {
        id: 172,
        nombre_id: 50,
        temporada: 1,
        nombre: "T1:E8.La pieza que falta",
        info: "El Hermano Día emprende un viaje que ningún otro Cleón ha intentado jamás. Salvor está dispuesta a hacer el máximo sacrificio para volver a su planeta.",
        caratula: "../../assets/portadas/foundation_portada.jpg",
        url: "../movies/foundation/s1/foundation0108.mp4",
    },
    {
        id: 173,
        nombre_id: 50,
        temporada: 1,
        nombre: "T1:E9.La primera crisis",
        info: "En Términus, el campo nulo ha adquirido aún más fuerza. El Hermano Despunte toma una atrevida decisión.",
        caratula: "../../assets/portadas/foundation_portada.jpg",
        url: "../movies/foundation/s1/foundation0109.mp4",
    },
    {
        id: 174,
        nombre_id: 50,
        temporada: 1,
        nombre: "T1:E10.El salto",
        info: "Final de la temporada. Un aliado inesperado ayuda a Salvor a forjar una alianza. Una confrontación entre los Hermanos tiene consecuencias inimaginables.",
        caratula: "../../assets/portadas/foundation_portada.jpg",
        url: "../movies/foundation/s1/foundation0110.mp4",
    },
    {
        id: 175,
        nombre_id: 50,
        temporada: 1,
        nombre: "T2:E1.A la sombra de Seldon",
        info: "Hari se encuentra atrapado en una prisión misteriosa. Un intento de magnicidio deja a Día alterado. Gaal y Salvor idean un plan de huida.",
        caratula: "../../assets/portadas/foundation_portada_s2.jpg",
        url: "../movies/foundation/s2/foundation0201.mp4",
    },
    {
        id: 176,
        nombre_id: 50,
        temporada: 2,
        nombre: "T2:E2.Un atisbo de la oscuridad\r\n",
        info: "Gaal tiene una visión inquietante. Se refuerza el vínculo de Día con la reina Sareth. La Bóveda se abre y revela un críptico mensaje.",
        caratula: "../../assets/portadas/foundation_portada_s2.jpg",
        url: "../movies/foundation/s2/foundation0202.mp4",
    },
    {
        id: 177,
        nombre_id: 50,
        temporada: 2,
        nombre: "T2:E3.Rey y plebeyo",
        info: "El Imperio recluta a Bel Riose para investigar a la renacida Fundación. Hari guía a Gaal y Salvor hacia un planeta desierto.",
        caratula: "../../assets/portadas/foundation_portada_s2.jpg",
        url: "../movies/foundation/s2/foundation0203.mp4",
    },
    {
        id: 178,
        nombre_id: 50,
        temporada: 2,
        nombre: "T2:E4.Donde hay menos estrellas",
        info: "La reina Sareth y Despunte se citan mientras ella trata de saber más cosas de Día. Los hermanos Constant y Poly llevan a Hober Mallow a Términus.",
        caratula: "../../assets/portadas/foundation_portada_s2.jpg",
        url: "../movies/foundation/s2/foundation0204.mp4",
    },
    {
        id: 179,
        nombre_id: 51,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/harta.mkv",
    },
    {
        id: 180,
        nombre_id: 52,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/fdbl.mkv",
    },
    {
        id: 181,
        nombre_id: 53,
        temporada: 1,
        nombre: "T1:E7.Especies complementarias\r\n",
        info: "Mientras Matabot gestiona unos efectos colaterales detecta una amenaza. Para evitar el peligro, el equipo se dirige a un espacio lleno de sorpresas.",
        caratula: "../../assets/portadas/murderbot_portada.webp",
        url: "../movies/murderbot/s1/murderbot0107.mp4",
    },
    {
        id: 182,
        nombre_id: 50,
        temporada: 2,
        nombre: "T2:E5.Los visuales y los vistos",
        info: "Gaal, Salvor y Hari llegan a Ignis y hallan la fuente de la extraña señal que han estado rastreando. Despunte y Descenso sospechan de Día.",
        caratula: "../../assets/portadas/foundation_portada_s2.jpg",
        url: "../movies/foundation/s2/foundation0205.mp4",
    },
    {
        id: 183,
        nombre_id: 50,
        temporada: 2,
        nombre: "T2:E6.Por que crearon el vino",
        info: "Día y la reina Sareth emiten un anuncio importante. Tellem siembra la semilla de la desconfianza entre Gaal y Hari. Hober Mallow llega a su destino.",
        caratula: "../../assets/portadas/foundation_portada_s2.jpg",
        url: "../movies/foundation/s2/foundation0206.mp4",
    },
    {
        id: 184,
        nombre_id: 50,
        temporada: 2,
        nombre: "T2:E7.Una muerte necesaria",
        info: "Salvor empieza a cuestionar la motivación de los mentálicos. La propuesta de Hober Mallow a las Espaciales encuentra resistencia. Los hermanos Constant y Poly son procesados.",
        caratula: "../../assets/portadas/foundation_portada_s2.jpg",
        url: "../movies/foundation/s2/foundation0207.mp4",
    },
    {
        id: 185,
        nombre_id: 50,
        temporada: 2,
        nombre: "T1:E8.La última emperatriz",
        info: "La prescriptora Rue confiesa a Descenso que recela de Demerzel. Hober Mallow intenta una jugada atrevida. Día pone rumbo a Términus y la Fundación.",
        caratula: "../../assets/portadas/foundation_portada_s2.jpg",
        url: "../movies/foundation/s2/foundation0208.mp4",
    },
    {
        id: 186,
        nombre_id: 50,
        temporada: 2,
        nombre: "T2:E9.Hace ya tiempo, no lejos de aquí",
        info: "Descenso y la prescriptora Rue se enteran del origen y la verdadera función de Demerzel. Los planes de Tellem para Gaal toman una deriva siniestra. En Términus, Día afronta al Dr. Seldon.",
        caratula: "../../assets/portadas/foundation_portada_s2.jpg",
        url: "../movies/foundation/s2/foundation0209.mp4",
    },
    {
        id: 187,
        nombre_id: 50,
        temporada: 2,
        nombre: "T2:E10.Mitos de la creación",
        info: "Gaal, Salvor y Hari trazan una nueva ruta para Ignis. Demerzel se dirige a Trántor y toma unas medidas que cambiarán el Imperio para siempre.",
        caratula: "../../assets/portadas/foundation_portada_s2.jpg",
        url: "../movies/foundation/s2/foundation0210.mp4",
    },
    {
        id: 188,
        nombre_id: 50,
        temporada: 3,
        nombre: "T3:E1.El Decimocuarto Día",
        info: "Disponible en: 11 de julio de 2025",
        caratula: "../../assets/portadas/foundation_portada_s3.jpg",
        url: "../movies/foundation/s3/foundation0301.mp4",
    },
    {
        id: 189,
        nombre_id: 17,
        temporada: 2,
        nombre: "T2:E1.Los Cuatro Notables",
        info: "María Anselmi (María Marull) y su padre (Atilio Pozzobón) son víctimas de un asalto a la salida de un cajero, haciendo que el hombre sufra una descompensación. Al momento de internarse, la prepaga se niega a cubrir los gastos del tratamiento, por considerar su deficiencia cardíaca como enfermedad preexistente. Tras hablar con su prima, Clara Molina, María contrata a los Simuladores para que la prepaga revea su postura.",
        caratula: "../../assets/portadas/simuladores_portada_s2.webp",
        url: "https://archive.org/download/los-simuladores-2002/T2-01.%20Los%20cuatro%20notables%20%5B480p%5D.ia.mp4",
    },
    {
        id: 190,
        nombre_id: 17,
        temporada: 2,
        nombre: "T2:E2.Z-9000",
        info: "Beatriz contrata a los Simuladores, quienes aprovechan la particularidad de que Carlos es sietemesino para elaborar un plan a su alrededor para alejarlo de ella.",
        caratula: "../../assets/portadas/simuladores_portada_s2.webp",
        url: "https://archive.org/download/los-simuladores-2002/T2-02.%20Z-9000%20%5B480p%5D.ia.mp4",
    },
    {
        id: 191,
        nombre_id: 17,
        temporada: 2,
        nombre: "T2:E3.La gargantilla de las cuatro estaciones",
        info: "Alejandro Barack (Federico Olivera) Por un lado, está en pareja con la joven Corina Lázaro (Eleonora Wexler), de quien asegura estar enamorado. Pero por otro lado, no concibe la idea de la fidelidad, por lo que se la pasa observando a otras mujeres. Con el fin de poder darle una solución a su problema contrata a los Simuladores. Si bien Santos le comunica que no tomará el caso, en realidad lo toma y trama un plan que provoque despertar los celos de Alejandro hacia Corina.",
        caratula: "../../assets/portadas/simuladores_portada_s2.webp",
        url: "https://archive.org/download/los-simuladores-2002/T2-03.%20La%20gargantilla%20de%20las%20cuatro%20estaciones%20%5B480p%5D.ia.mp4",
    },
    {
        id: 192,
        nombre_id: 17,
        temporada: 2,
        nombre: "T2:E4.El Clan Motul",
        info: "un viejo y fornido colaborador los contrata para encargarse de un maestro jardinero que maltrata a los niños. Mientras tanto, Milazzo seduce a una azafata que estuvo en el avión donde los Simuladores detuvieron al terrorista y consigue los nombre de los cuatro miembros.",
        caratula: "../../assets/portadas/simuladores_portada_s2.webp",
        url: "https://archive.org/download/los-simuladores-2002/T2-04.%20El%20clan%20Motul%20%5B480p%5D.ia.mp4",
    },
    {
        id: 193,
        nombre_id: 17,
        temporada: 2,
        nombre: "T2:E5.El Vengador Infantil",
        info: "un inepto e inescrupuloso comerciante que buscaba saltearse los trámites de habilitación para instalar una casa de videojuegos, y que tras perder el dinero, había pedido ayuda a los Simuladores. Sin embargo, Santos le informa a Perillo que su dinero fue reinvertido en una pequeña editorial de cómics, al frente de la cual es puesto el propio Perillo.",
        caratula: "../../assets/portadas/simuladores_portada_s2.webp",
        url: "https://archive.org/download/los-simuladores-2002/T2-05.%20El%20vengador%20infantil%20%5B480p%5D.ia.mp4",
    },
    {
        id: 194,
        nombre_id: 54,
        temporada: 1,
        nombre: "T1:E1.Dulcinea",
        info: "En el cinturón de asteroides cercano a Saturno, James Holden y la tripulación del carguero de hielo, el Canterbury, de camino a Ceres, investigan una llamada de auxilio de un derrelicto desconocido, el Scopuli.\r\n",
        caratula: "../../assets/portadas/expanse_caratula.webp",
        url: "../movies/expanse/s1/theexpanse0101.mp4",
    },
    {
        id: 195,
        nombre_id: 54,
        temporada: 1,
        nombre: "T1:E2.El Gran Vacio",
        info: "Holden y la tripulación luchan por sobrevivir en un transbordador arruinado, el Caballero. En la estación de Ceres, Miller tiene más problemas de los que esperaba para rastrear a Julie Mao, especialmente cuando descubre que esta tiene conexiones con la Alianza de Planetas Exteriores: un grupo político extremista que lucha por los derechos de las colonias del Cinturón de asteroides.",
        caratula: "../../assets/portadas/expanse_caratula.webp",
        url: "../movies/expanse/s1/theexpanse0102.mp4",
    },
    {
        id: 196,
        nombre_id: 54,
        temporada: 1,
        nombre: "T1:E3.Recuerda lo Imposible",
        info: "Toman prisioneros e interrogan a Holden y a la tripulación en el buque insignia marciano, el Donnager. Pronto se traicionarán los unos a los otros.",
        caratula: "../../assets/portadas/expanse_caratula.webp",
        url: "../movies/expanse/s1/theexpanse0103.mp4",
    },
    {
        id: 197,
        nombre_id: 54,
        temporada: 1,
        nombre: "T1:E4.Combate en Espacio",
        info: "Holden y la tripulación quedan atrapados en medio de una batalla desesperada en la que naves de guerra misteriosas atacan y abordan el Donnager.",
        caratula: "../../assets/portadas/expanse_caratula.webp",
        url: "../movies/expanse/s1/theexpanse0104.mp4",
    },
    {
        id: 198,
        nombre_id: 54,
        temporada: 1,
        nombre: "T1:E5.Volver al Carnicero",
        info: "Holden y la tripulación cierran un trato con un aliado impensado en la estación Tycho.\r\n",
        caratula: "../../assets/portadas/expanse_caratula.webp",
        url: "../movies/expanse/s1/theexpanse0105.mp4",
    },
    {
        id: 199,
        nombre_id: 55,
        temporada: 3,
        nombre: "T3:E1. «Llaves y cuchillos»",
        info: "No‑eul ejecuta un plan arriesgado para infiltrarse en una peligrosa operación. Se anuncia el próximo juego: las escondidas, en el que un grupo tiene llaves, y el otro, cuchillos.",
        caratula: "../../assets/portadas/squid_portada_s3.webp",
        url: "../movies/squid/s3/squid0301.mp4",
    },
    {
        id: 200,
        nombre_id: 55,
        temporada: 3,
        nombre: "T3:E2. «Noche estrellada»",
        info: "Los juegos siguen su curso, y Gi‑hun se empeña en confrontar a Kang Dae‑ho. Mientras, Kim Jun‑hee se enfrenta a una crisis que pondrá a prueba los límites de su determinación.",
        caratula: "../../assets/portadas/squid_portada_s3.webp",
        url: "../movies/squid/s3/squid0302.mp4",
    },
    {
        id: 201,
        nombre_id: 55,
        temporada: 3,
        nombre: "T3:E3. «No es culpa tuya»",
        info: "El equipo de Jun‑ho se acerca cada vez más a la isla. Jang Geum‑ja le hace un pedido desesperado a Gi‑hun para ayudar a Jun‑hee. Los VIP debaten una infame propuesta.",
        caratula: "../../assets/portadas/squid_portada_s3.webp",
        url: "../movies/squid/s3/squid0303.mp4",
    },
    {
        id: 202,
        nombre_id: 55,
        temporada: 3,
        nombre: "T3:E4. «222»",
        info: "Incluso con el apoyo de Gi‑hun entre tanta presión. Jun‑hee debe tomar una decisión crucial. Antes del juego final, el líder le da un ultimátum a Gi‑hun.",
        caratula: "../../assets/portadas/squid_portada_s3.webp",
        url: "../movies/squid/s3/squid0304.mp4",
    },
    {
        id: 203,
        nombre_id: 55,
        temporada: 3,
        nombre: "T3:E5. «○△□»",
        info: "No‑eul trata de obtener una ventaja en las negociaciones, pero sus planes salen mal. Gi‑hun se enfrenta a un dilema ético. Con sus límites a prueba, ¿qué tan lejos podrá ir?\r\n\r\n",
        caratula: "../../assets/portadas/squid_portada_s3.webp",
        url: "../movies/squid/s3/squid0305.mp4",
    },
    {
        id: 204,
        nombre_id: 55,
        temporada: 3,
        nombre: "T3:E6.«La naturaleza humana»",
        info: "Jun‑ho se apresura para llegar a la isla mientras la tensión llega al punto más alto en la ronda final. Los jugadores se enfrentan a una situación imposible en los últimos minutos del juego.",
        caratula: "../../assets/portadas/squid_portada_s3.webp",
        url: "../movies/squid/s3/squid0306.mp4",
    },
    {
        id: 205,
        nombre_id: 56,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/amateur.mkv",
    },
    {
        id: 206,
        nombre_id: 57,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/dragon.mkv",
    },
    {
        id: 207,
        nombre_id: 58,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/karate.mkv",
    },
    {
        id: 208,
        nombre_id: 59,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/ballerina.mkv",
    },
    {
        id: 209,
        nombre_id: 60,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/devuelvela.mp4",
    },
    {
        id: 210,
        nombre_id: 61,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/ritual.mp4",
    },
    {
        id: 211,
        nombre_id: 53,
        temporada: 1,
        nombre: "T1:E8. Objeto Extraño",
        info: "PresAux recibe el mensaje de un grupo rival. Gurathin examina el pasado sangriendo de Matabot.",
        caratula: "../../assets/portadas/murderbot_portada.webp",
        url: "../movies/murderbot/s1/murderbot0108.mp4",
    },
    {
        id: 212,
        nombre_id: 62,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/guardia.mkv",
    },
    {
        id: 213,
        nombre_id: 63,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/worldos.mkv",
    },
    {
        id: 214,
        nombre_id: 64,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/sentencia.mkv",
    },
    {
        id: 215,
        nombre_id: 53,
        temporada: 1,
        nombre: "T1:E9.Sistema Critico",
        info: "Matabot dirige una reunión crítica. Gurathin y Pin-Lee idean un plan. Mensah se la juega por su cuenta.",
        caratula: "../../assets/portadas/murderbot_portada.webp",
        url: "../movies/murderbot/s1/murderbot0109.mp4",
    },
    {
        id: 216,
        nombre_id: 65,
        temporada: 1,
        nombre: null,
        info: null,
        caratula: null,
        url: "../movies/jefes.mkv",
    },
    {
        id: 217,
        nombre_id: 17,
        temporada: 2,
        nombre: "T2:E6.El matrimonio mixto",
        info: "Un joven judío y una chica católica buscan ayuda para convencer a sus familias de que su matrimonio es una buena idea. El grupo orquesta un operativo para que ambas familias acepten la unión.",
        caratula: "../../assets/portadas/simuladores_portada_s2.webp",
        url: "https://archive.org/download/los-simuladores-2002/T2-06.%20El%20matrimonio%20mixto%20%5B480p%5D.ia.mp4",
    },
    {
        id: 218,
        nombre_id: 17,
        temporada: 2,
        nombre: "T2:E7.La brigada B",
        info: "La 'Brigada B', formada por antiguos clientes, es capturada por el FBI durante una simulación. Los Simuladores originales deben infiltrarse para rescatarlos del sistema de seguridad más inteligente del mundo.",
        caratula: "../../assets/portadas/simuladores_portada_s2.webp",
        url: "https://archive.org/download/los-simuladores-2002/T2-07.%20La%20brigada%20B%20%5B480p%5D.ia.mp4",
    },
    {
        id: 219,
        nombre_id: 17,
        temporada: 2,
        nombre: "T2:E8.Fin de semana de descanso",
        info: "Durante unas vacaciones en Entre Ríos, el equipo presencia un supuesto accidente mortal. Al investigar, descubren que se trata de un simulacro para encubrir un homicidio real cometido en el hotel.",
        caratula: "../../assets/portadas/simuladores_portada_s2.webp",
        url: "https://archive.org/download/los-simuladores-2002/T2-08.%20Fin%20de%20semana%20de%20descanso%20%5B480p%5D.ia.mp4",
    },
    {
        id: 220,
        nombre_id: 17,
        temporada: 2,
        nombre: "T2:E9.El debilitador social",
        info: "Para ayudar a una modelo con bulimia, el grupo simula un tribunal de la ONU que juzga al jefe de su agencia por crímenes contra la humanidad, exponiendo la crueldad de la industria de la moda.",
        caratula: "../../assets/portadas/simuladores_portada_s2.webp",
        url: "https://archive.org/download/los-simuladores-2002/T2-09.%20El%20debilitador%20social%20%5B480p%5D.ia.mp4",
    },
    {
        id: 221,
        nombre_id: 17,
        temporada: 2,
        nombre: "T2:E10.El anillo de Salomón",
        info: "Un reconocido director de orquesta es extorsionado por un joven ambicioso. El equipo interviene para liberar al maestro de la presión opresiva de su supuesto protegido.",
        caratula: "../../assets/portadas/simuladores_portada_s2.webp",
        url: "https://archive.org/download/los-simuladores-2002/T2-10.%20El%20anillo%20de%20Salom%C3%B3n%20%5B480p%5D.ia.mp4",
    },
    {
        id: 222,
        nombre_id: 17,
        temporada: 2,
        nombre: "T2:E11.Episodio final",
        info: "En su último caso, el grupo ayuda a un hombre de 35 años a independizarse. Mientras tanto, un viejo enemigo vuelve para vengarse y los Simuladores deben decidir su futuro como equipo.",
        caratula: "../../assets/portadas/simuladores_portada_s2.webp",
        url: "https://archive.org/download/los-simuladores-2002/T2-11.%20Episodio%20final%20%5B480p%5D.ia.mp4",
    },
];
