const series = [
    {
        id: 1,
        nombre: "The Last Of Us",
        descripcion: "Drama - 2023\r\nSerie posapocalíptica inspirada en el aclamado videojuego que sigue la brutal y desgarradora travesía de un hombre cínico y una joven de 14 años.",
        poster: "../../assets/posters/tlou_poster.webp",
        isotipo: "../assets/portadas/tlou_isotipo.avif",
        tipo: "serie",
    },
    {
        id: 2,
        nombre: "YellowJackets",
        descripcion: "Thriller - 2021\r\nLas talentosas jugadoras de un equipo de futbol de secundaria, se convierten en las (des)afortunadas sobrevivientes de un accidente aereo en las entrañas de un bosque en Ontario.",
        poster: "../../assets/posters/yellowjackets_poster.jpeg",
        isotipo: null,
        tipo: "serie",
    },
    {
        id: 3,
        nombre: "Moana 2",
        descripcion: "Animacion - 2024\r\nDespués de recibir una llamada inesperada de sus antepasados de referencia, Moana debe viajar a los mares lejanos de Oceanía y a aguas peligrosas y perdidas durante mucho tiempo, una aventura diferente a otras que haya enfrentado.",
        poster: "../../assets/posters/moanados_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 4,
        nombre: "Sonic 3",
        descripcion: "Aventuras - 2025\r\nSonic, Knuckles y Tails se reunirán para enfrentarse a un nuevo y poderoso adversario, Shadow, un misterioso villano con poderes nunca antes vistos.",
        poster: "../../assets/posters/sonic3.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 5,
        nombre: "Martín Fierro",
        descripcion: "Western - 1968\r\nEl gaucho Martín Fierro es llevado por el gobierno a la fuerza para integrar las milicias y luchar contra los indios, cuando vuelve ha perdido a su familia y su rancho. La pena lo lleva a volverse \"gaucho matrero\"",
        poster: "../../assets/posters/martinfierro_poster.jpeg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 6,
        nombre: "El Abismo Secreto",
        descripcion: "Sci-Fi - 2025\r\nMandan a dos operativos de élite a vigilar lados opuestos de un misterioso abismo y allí intiman desde la distancia, pero deberán aunar fuerzas para sobrevivir al mal que esconde el abismo.",
        poster: "../../assets/posters/thegorge.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 7,
        nombre: "Los Increibles",
        descripcion: "Animacion - 2001\r\nlos Parr son una familia de superheroe, que llevan un estilo de vida suburbano ante las restricciones gubernamentales impuestas tras considerarse que sus hazañas conllevan situaciones problemáticas para la sociedad.",
        poster: "../../assets/posters/increibles_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 8,
        nombre: "Mufasa: El Rey León",
        descripcion: "Animacion - 2025\r\nA través del relato del mandril Rafiki a la pequeña Kiara, hija de Simba y Nala, conocemos cómo Mufasa, un cachorro huérfano, es adoptado por la familia del príncipe Taka y cómo una serie de sucesos lo lleva a ser nombrado rey.",
        poster: "../../assets/posters/mufasa_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 9,
        nombre: "La Cordillera",
        descripcion: "Suspenso - 2017\r\nEn una cumbre de presidentes latinoamericanos en Chile, donde se trazan las estrategias geopolíticas y las alianzas, Hernán Blanco, el presidente de Argentina, atraviesa un drama político y familiar. Está implicado en un caso de corrupción a través de su yerno.",
        poster: "../../assets/posters/cordillera_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 10,
        nombre: "Gladiador 2",
        descripcion: "Accion - 2024\r\nAños después de presenciar la muerte del venerado héroe Maximus a manos de su tío, Lucius (Paul Mescal) se ve obligado a ingresar al Coliseo después de que su hogar fuera conquistado por los emperadores tiránicos que ahora dirigen Roma con mano de hierro.",
        poster: "../../assets/posters/gladiador2_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 11,
        nombre: "Naked Gun",
        descripcion: "Comedia - 1988\r\nEl teniente Frank Debin busca al jefe de una banda de narcotraficantes para vengarse por haber herido a su compañero en un tiroteo..",
        poster: "../../assets/posters/naked_gun_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 12,
        nombre: "Paranormal Activity 7",
        descripcion: "Terror - 2021\r\nUna documentalista sigue a Margot mientras se dirige a una apartada comunidad Amish con la esperanza de aprender sobre su familia. Tras una serie de extraños sucesos, pronto se da cuenta de que esta comunidad podría esconder algo siniestro",
        poster: "../../assets/posters/nok_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 13,
        nombre: "Paranormal Activity 3",
        descripcion: "Terror - 2011\r\nDespués de mudarse a una casa suburbana, una pareja se inquieta cada vez más por una presencia demoníaca nocturna.",
        poster: "../../assets/posters/markedones_poster.webp",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 14,
        nombre: "Paranormal Activity 6",
        descripcion: "Terror - 2015\r\nLa Dimensión Fantasma es la sexta entrega de la saga de películas de terror Paranormal Activity. En ella, una familia se muda a una casa donde encuentran cintas de video que revelan la presencia de un antiguo mal.",
        poster: "../../assets/posters/dimension_desc_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 15,
        nombre: "The Electric State",
        descripcion: "Sci-Fi - 2025\r\nDe la mano de un robot, un contrabandista y su ocurrente compañero, una adolescente huérfana emprende un inolvidable viaje en busca de su hermano menor desaparecido.",
        poster: "../../assets/posters/electric_state_poster.jpeg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 16,
        nombre: "Severance",
        descripcion: "Suspenso - 2022\r\nEn esta serie ganadora al Emmy® del director Ben Stiller, Mark lidera a un equipo de oficinistas cuyas memorias han sido divididas quirúrgicamente entre su trabajo y vidas personales. Se embarcan en un viaje para descubrir la verdad sobre su trabajo… y ellos mismos.",
        poster: "../../assets/posters/severance_poster.jpg",
        isotipo: null,
        tipo: "serie",
    },
    {
        id: 17,
        nombre: "Los Simuladores",
        descripcion: "Ingenio - 2002\r\nTeleserie argentina en torno a un grupo de cuatro socios que se dedican al negocio de la \"simulación\", resolviendo los problemas y necesidades de sus clientes mediante lo que ellos denominan \"operativos de simulación\", que suelen consistir en engañar a quienes generan los problemas de sus clientes",
        poster: "../../assets/posters/simuladores_poster.jpg",
        isotipo: null,
        tipo: "serie",
    },
    {
        id: 19,
        nombre: "Relatos salvajes",
        descripcion: "Drama - 2014\r\nUna bárbara propuesta compuesta de seis relatos cortos escritos y dirigidos por Damián Szifron, que mezclan el drama con la comedia negra",
        poster: "../../assets/posters/relatos_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 21,
        nombre: "From",
        descripcion: "Terror - 2022\r\nFrom es una serie de terror y ciencia ficción sobre un pueblo misterioso que atrapa a las personas que entran. Los residentes deben sobrevivir a las amenazas del bosque y a criaturas sobrenaturales que aparecen cada noche",
        poster: "../../assets/posters/from_posters.jpg",
        isotipo: null,
        tipo: "serie",
    },
    {
        id: 22,
        nombre: "Reacher",
        descripcion: "Acción - 2022\r\nReacher viaja a Maine en búsqueda de un enemigo mortal y termina enredado con unos agentes de la DEA que actúan por cuenta propia, asesinos peligrosos y un misterioso negocio familiar.",
        poster: "../../assets/posters/reacher_poster.jpg",
        isotipo: null,
        tipo: "serie",
    },
    {
        id: 23,
        nombre: "Adolesence",
        descripcion: "Drama - 2025\r\nCuando un chico de 13 años es acusado de asesinar a una compañera de clase, su familia, su terapeuta y el detective a cargo se preguntan qué pasó en realidad.",
        poster: "../../assets/posters/ad_poster.jpg",
        isotipo: null,
        tipo: "serie",
    },
    {
        id: 24,
        nombre: "Mickey 17",
        descripcion: "Sci-Fi - 2025\r\nUn humano nombrado como un prescindible, es decir, un empleado desechable de una expedición para colonizar el mundo helado de Nilfheim",
        poster: "../../assets/posters/miky_poster.webp",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 26,
        nombre: "Destino Final 3",
        descripcion: "Terror - 2006\r\nUn grupo de estudiantes y amigos deben enfrentar las repercusiones tras haberse burlado de la muerte y sobrevivir a un terrible accidente en una montaña rusa.",
        poster: "../../assets/posters/fd3_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 27,
        nombre: "Destino Final 4",
        descripcion: "Terror - 2009\r\nUn grupo de amigos acude a un circuito de carreras. Durante la competencia, Nick tiene una premonición sobre un accidente y saca a sus amigos del recinto para escapar de la tragedia.",
        poster: "../../assets/posters/fd4_poster.webp",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 28,
        nombre: "Destino Final 5",
        descripcion: "Terror - 2011\r\nLa premonición de un hombre salva a varias personas del fatal colapso de un puente y varias almas desafortunadas descubren que la muerte no puede ser engañada.",
        poster: "../../assets/posters/fd5_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 29,
        nombre: "Capitán América: Brave New World",
        descripcion: "Marvel - 2025\r\nTras reunirse con el presidente Thaddeus Ross, Sam se encuentra en medio de un incidente internacional y deberá descubrir los motivos detrás de una conspiración global.\r\n",
        poster: "../../assets/posters/capambnw_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 30,
        nombre: "Novocaine",
        descripcion: "Accioón - 2025\r\nLa chica de los sueños de un hombre es secuestrada, haciendo que su incapacidad para sentir dolor se convierta en una ventaja inesperada al luchar contra una banda de matones para rescatarla.",
        poster: "../../assets/posters/novo_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 32,
        nombre: "A working Man",
        descripcion: "Accion - 2025\r\nLevon dejó atrás un pasado marcado por la violencia para ser un buen ejemplo para su hija. Sin embargo, cuando la hija de su jefe desaparece, este antiguo militar de élite no se detendrá ante nada.",
        poster: "../../assets/posters/awman_poster.webp",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 33,
        nombre: "Y Donde Esta El policía 2",
        descripcion: "Comedia - 1991\r\nEl teniente de la policía, Frank Drebbin, se enfrente a los magnates corruptos de las industrias energéticas.",
        poster: "../../assets/posters/idepol_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 34,
        nombre: "Ash",
        descripcion: "Sci-Fi - 2025\r\nUna científica de la estación espacial Riya se despierta y descubre que sus colegas han sido asesinados brutalmente. Junto con Brion.",
        poster: "../../assets/posters/ash_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 35,
        nombre: "Donde Está El Policía 3",
        descripcion: "Comedia - 1994\r\nFrank Drebin vuelve de su retiro para intentar colaborar con la policía e infiltrarse en una pandilla de terroristas que intenta detonar una bomba.",
        poster: "../../assets/posters/ngtree_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 36,
        nombre: "El Eternauta",
        descripcion: "Sci-Fi - 2025\r\nDespués de una nevada mortal que acaba con gran parte de la población, Juan Salvo y un grupo de sobrevivientes en Buenos Aires deben resistir a una amenaza de otro planeta.",
        poster: "../../assets/posters/eternauta_poster.jpg",
        isotipo: "../assets/portadas/eternauta_isotipo.png",
        tipo: "serie",
    },
    {
        id: 37,
        nombre: "Cónclave",
        descripcion: "Drama - 2024\r\nTras la muerte del Papa, el cardenal Lawrence, partícipe en el cónclave en el que se elige al sucesor, descubre un secreto que pondrá en peligro los cimientos de la Iglesia católica.",
        poster: "../../assets/posters/conclave_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 38,
        nombre: "El Mono",
        descripcion: "Terror - 2025\r\nDos hermanos gemelos encuentran un misterioso mono de cuerda y una serie de muertes atroces separan a su familia.",
        poster: "../../assets/posters/mono_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 40,
        nombre: "Minecraft: The Movie",
        descripcion: "Sci-Fi - 2025\r\nCuatro inadaptados son arrastrados por un portal al Overworld, un misterioso lugar que se nutre de la imaginación.",
        poster: "../../assets/posters/minecraft_poster.jpg",
        isotipo: "../assets/portadas/minecraft_isotipo.png",
        tipo: "pelicula",
    },
    {
        id: 41,
        nombre: "Warfare",
        descripcion: "Accion - 2025\r\nLa desgarradora historia real de una misión de vigilancia de un pelotón de los Navy Seals de EE. UU. que salió peligrosamente mal. Warfare captura la intensidad del combate como nunca antes y ofrece un retrato inquebrantable de la hermandad, el sacrificio y la supervivencia.",
        poster: "../../assets/posters/war_poster.jpg",
        isotipo: "../assets/portadas/warfare_isotipo.jpg",
        tipo: "pelicula",
    },
    {
        id: 42,
        nombre: "Blanca Nieves",
        descripcion: "Animación - 2025\r\nSnow White​ es una película de fantasía musical estadounidense dirigida por Marc Webb, a partir de un guion de Greta Gerwig y Erin Cressida Wilson.",
        poster: "../../assets/posters/white_poster.webp",
        isotipo: "../assets/portadas/white_isotipo.png",
        tipo: "pelicula",
    },
    {
        id: 43,
        nombre: "SuperHero: Movie",
        descripcion: "Parodia - 2008\r\nParodia de las películas de superhéroes, como Spiderman, Batman o Los 4 Fantásticos. En esta ocasión la historia se centra en Rick Riker, un joven agradable pero muy torpe que adquiere superpoderes accidentalmente.",
        poster: "../../assets/posters/superhero_poster.jpg",
        isotipo: "../assets/portadas/superhero_isotipo.png",
        tipo: "pelicula",
    },
    {
        id: 44,
        nombre: "Acusado Sin Razón",
        descripcion: "Comedia - 1998\r\nUn violinista que es acusado falsamente de matar a su benefactor trata de probar su inocencia mientras huye.",
        poster: "../../assets/posters/acused_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 45,
        nombre: "Until Dawn: Noche de Terror",
        descripcion: "Thriller - 2025\r\nUntil Dawn es una película de terror estadounidense, dirigida por David F. Sandberg a partir de un guion de Gary Dauberman. Está basado en el videojuego de 2015 del mismo título desarrollado por Supermassive Games.",
        poster: "../../assets/posters/untildawn_poster.jpg",
        isotipo: "../assets/portadas/untildawn_isotipo.png",
        tipo: "pelicula",
    },
    {
        id: 46,
        nombre: "Lilo & Stitch",
        descripcion: "Animación - 2025\r\nRemake en imagen real de \"Lilo & Stitch\". Narra la historia de una niña hawaiana solitaria y un extraterrestre fugitivo que la ayuda a recomponer su rota familia",
        poster: "../../assets/posters/stitch_poster.jpg",
        isotipo: "../assets/portadas/stitch_isotipo.png",
        tipo: "pelicula",
    },
    {
        id: 47,
        nombre: "Invasion",
        descripcion: "Sci-Fi - 2021\r\nInvasión es una ambiciosa serie dramática de ciencia ficción que sigue una invasión alienígena a través de distintas perspectivas alrededor del mundo.",
        poster: "../../assets/posters/invasion_poster.jpg",
        isotipo: null,
        tipo: "serie",
    },
    {
        id: 48,
        nombre: "Arcane",
        descripcion: "Animacion - 2024\r\nMientras la discordia separa las ciudades gemelas de Piltóver y Zaun, dos hermanas se enfrentan en una guerra feroz entre tecnologías mágicas y convicciones opuestas.",
        poster: "../../assets/posters/arcane_poster.jpg",
        isotipo: "../assets/portadas/arcane_isotipo.webp",
        tipo: "serie",
    },
    {
        id: 49,
        nombre: "La Fuente de la Juventud",
        descripcion: "Accion - 2025\r\nUn genio cazatesoros (John Krasinski) reúne a un equipo para una misión que cambiará vidas. Pero para esquivar y superar los obstáculos que se encontrará, necesitará a alguien más listo que él: su distanciada hermana (Natalie Portman).",
        poster: "../../assets/posters/juventud_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 50,
        nombre: "Foundation",
        descripcion: "Sci-Fi - 2021\r\nBasada en las premiadas novelas de Isaac Asimov, “Foundation” gira en torno a un grupo de exiliados en su afán por salvar la humanidad y reconstruir la civilización ante la caída del Imperio Galáctico.",
        poster: "../../assets/posters/foundation_poster.png",
        isotipo: "../assets/portadas/foundation_isotipo.webp",
        tipo: "serie",
    },
    {
        id: 51,
        nombre: "Harta",
        descripcion: "Drama - 2025\r\n¿Cuál será la gota que colmará el vaso? Un día terriblemente malo lleva a una madre sola muy trabajadora al límite… y a cometer un sorprendente acto de desesperación.",
        poster: "../../assets/posters/harta_poster.webp",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 52,
        nombre: "Destino Final 6: Bloodlines",
        descripcion: "Terror - 2025\r\nAtormentada por una violenta pesadilla recurrente, Stefani regresa a su hogar para encontrar a la única persona que podría romper el ciclo y salvar a su familia.",
        poster: "../../assets/posters/bloodlines_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 53,
        nombre: "MurderBot",
        descripcion: "Sci-Fi - 2025\r\n«Matabot», serie basada en la saga de Martha Wells de novelas superventas ganadoras de premios Hugo y Nebula, es un thriller de ciencia ficción con toques de comedia sobre un androide de seguridad horrorizado por las emociones humanas pero atraido por sus clientes más vulnerables. Matabot debe camuflar su libre albedrío y completar una misión peligrosa cuando lo único que quiere es que lo dejen solo para ver telenovelas futuristas y descubrir cuál es su lugar en el universo.",
        poster: "../../assets/posters/murderbot_poster.jpg",
        isotipo: null,
        tipo: "serie",
    },
    {
        id: 54,
        nombre: "The Expanse",
        descripcion: "Sci-Fi - 2015\r\nCientos de años en el futuro, las cosas son diferentes después de que los seres humanos colonizan el sistema solar y Marte se ha convertido en una potencia militar independiente. Las crecientes tensiones entre la Tierra y Marte las han puesto al borde de la guerra",
        poster: "../../assets/posters/expanse_poster.jpg",
        isotipo: "../assets/portadas/expanse_isotipo.webp",
        tipo: "serie",
    },
    {
        id: 55,
        nombre: "Squid Games",
        descripcion: "Suspenso - 2021\r\nCientos de personas con dificultades económicas aceptan una extraña invitación a un juego de supervivencia. Les espera un premio millonario, pero hay mucho en juego.",
        poster: "../../assets/posters/squid_poster.jpg",
        isotipo: "../assets/portadas/squid_isotipo.png",
        tipo: "serie",
    },
    {
        id: 56,
        nombre: "The Amateur",
        descripcion: "Accion - 2025\r\nCharlie Heller es un criptógrafo de la CIA que emprende un peligroso viaje en busca de los asesinos de su esposa.",
        poster: "../../assets/posters/amateur_poster.webp",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 57,
        nombre: "Como Entrenar a tu Dragon",
        descripcion: "Live-Action - 2025\r\nUn niño vikingo llamado Hipo desafía la tradición al hacerse amigo de un dragón llamado Chimuelo. Cuando surge una antigua amenaza que pone en peligro a ambas especies, la amistad de Hipo con Chimuelo se convierte en la clave para un nuevo futuro.",
        poster: "../../assets/posters/dragon.webp",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 58,
        nombre: "Karate Kids: Legends",
        descripcion: "Accion - 2025\r\nDaniel llega a Beijing y descubre que Han tiene un nuevo protegido, Li Fong. Los dos mentores deben colaborar y ajustar enfoques educativos para preparar a Li Fong.",
        poster: "../../assets/posters/karate_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 59,
        nombre: "Ballerina",
        descripcion: "Accion - 2025\r\nUna asesina entrenada en las tradiciones de la organización Ruska Roma busca venganza tras la muerte de su padre.",
        poster: "../../assets/posters/ballerina_poster.jpg",
        isotipo: "../assets/portadas/ballerina_isotipo.png",
        tipo: "pelicula",
    },
    {
        id: 60,
        nombre: "Bring Her Back",
        descripcion: "Terror - 2025\r\nBring Her Back es una película australiana de terror sobrenatural de 2025, dirigida por Danny y Michael Philippou, y escrita por Danny Philippou y Bill Hinzman.",
        poster: "../../assets/posters/devuelvela_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 61,
        nombre: "The Ritual",
        descripcion: "Terror - 2025\r\nThe Ritual es una película de terror estadounidense de 2025 dirigida y coescrita por David Midell. Basada en una historia real, sigue a los sacerdotes Theophilus Riesinger y Joseph Steiger mientras",
        poster: "../../assets/posters/ritual_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 62,
        nombre: "La Vieja Guardia 2",
        descripcion: "Accion - 2025\r\nTraducción del inglés-La Vieja Guardia 2 es una película estadounidense de superhéroes de 2025 dirigida por Victoria Mahoney, con guion de Greg Rucka y Sarah L. Walker, basada en su cómic La Vieja Guardia.",
        poster: "../../assets/posters/guardia_poster.jpeg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 63,
        nombre: "Jurassic World: Rebirth",
        descripcion: "Sci-Fi - 2025\r\nOperadores viajan a una instalación de investigación en la isla para asegurar el ADN que salva vidas de los dinosaurios. La misión se vuelve cada vez más peligrosa, y pronto descubren un siniestro e impactante secreto.",
        poster: "../../assets/posters/worldos_poster.jpg",
        isotipo: null,
        tipo: "pelicula",
    },
    {
        id: 64,
        nombre: "Mision Imposible: Sentencia Final",
        descripcion: "Accion - 2025\r\nLas nuevas aventuras del agente del FMI y líder de un equipo de operativos, Ethan Hunt.\r\n",
        poster: "../../assets/posters/sentencia_poster.jpg",
        isotipo: null,
        tipo: "Pelicula",
    },
    {
        id: 65,
        nombre: "Jefes de Estado",
        descripcion: "Accion - 2025\r\nEl Primer Ministro del Reino Unido y el Presidente de los Estados Unidos mantienen una rivalidad pública que pone en peligro la alianza de sus países. Pero cuando se convierten en objetivos de un poderoso enemigo, se ven obligados a colaborar.",
        poster: "../../assets/posters/jefes_poster.jpg",
        isotipo: null,
        tipo: "peliculas",
    },
    {
        id: 66,
        nombre: "Casados con Hijos",
        descripcion: "Comedia - 2005\r\nLa vida de los Argento, una familia de clase media baja, se ve alterada por las situaciones que enfrentan en su día a día.",
        poster: "../../assets/posters/casados_poster.webp",
        isotipo: null,
        tipo: "serie",
    },
];

